spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        new_generator_mappings: false
        format_sql: true
        enable_lazy_load_no_trans: true
    open-in-view: false
  datasource:
    url: jdbc:sqlserver://localhost:1433;instance=MSSQLSERVER;TRUSTED_CONNECTION=TRUE;database=movie_test
    username: movietest
    password: movietest
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
